MBSR_App/urls.py
from django.urls import include, path, re_path

from . import views
from mbsr_app.views import (
    GettingStartedCreateView, FormalPracticeCreateView, InformalPracticeCreateView, 
    IndexView, SignUpView, MyLoginView, AccountHomeView, MyLogoutView, AccountHomeRedirectView, 
    FormalPracticeDetailView, InformalPracticeDetailView, InformalPracticeListView, FormalPracticeListView,
    GettingStartedDetailView
)
from django.contrib.auth import views as auth_views

app_name = 'mbsr_app'
urlpatterns = [
    path('', IndexView.as_view(), name='index'),
    
    path('getting_started_create_view/', GettingStartedCreateView.as_view(), name='getting_started_create_view'),
    path('getting_started_detail_view/', GettingStartedDetailView.as_view(), name='getting_started_detail_view'),
    path('formal_practice_create_view/', FormalPracticeCreateView.as_view(), name='formal_practice_create_view'),
    path('formal_practice_list_view/', FormalPracticeListView.as_view(), name='formal_practice_list_view'),
    path('formal_practice_detail_view/<date>/', FormalPracticeDetailView.as_view(), name='formal_practice_detail_view'),
    path('informal_practice_create_view/', InformalPracticeCreateView.as_view(), name='informal_practice_create_view'),
    path('informal_practice_list_view/', InformalPracticeListView.as_view(), name='informal_practice_list_view'),
    path('informal_practice_detail_view/<date>/', InformalPracticeDetailView.as_view(), name='informal_practice_detail_view'),
    path('signup_view/', SignUpView.as_view(), name='signup_view'),
    # path('login_view/', LogInView.as_view(), name='login_view'),
    path('account_home_view/<pk>/', AccountHomeView.as_view(), name='account_home_view'),
    path('login/', MyLoginView.as_view(template_name='mbsr_app/login.html'), name="login"),
    path('logout/', MyLogoutView.as_view(), name="logout"),
    # path('logout/', views.logout , name="logout"),
    path('account_view_redirect/', AccountHomeRedirectView.as_view(), name="account_view_redirect"),
    # path('accounts/', include('django.contrib.auth.urls')),
] 



handler404 = 'mbsr_app.views.not_found_404'
# handler500 = 'MBSR_App.views.my_custom_error_view'
# handler403 = 'MBSR_App.views.my_custom_permission_denied_view'
# handler400 = 'MBSR_App.views.my_custom_bad_request_view'

MBSR_Project/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mbsr/', include('mbsr_app.urls')),
]

handler404 = 'mbsr_app.views.not_found_404'

MBSR_App/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UsernameField, UserCreationForm
from .models import *

class MyUserCreationForm(UserCreationForm):
    password1 = forms.CharField(
        label= ("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "class": "input"}),
    )
    password2 = forms.CharField(
        label= ("Password confirmation"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "class": "input"}),
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if self._meta.model.USERNAME_FIELD in self.fields:
            self.fields[self._meta.model.USERNAME_FIELD].widget.attrs[
                "class"
            ] = "input"

class MyLoginForm(AuthenticationForm):
    username = UsernameField(widget=forms.TextInput(attrs={"autofocus": True, "class": "input"}))
    password = forms.CharField(
        label= ("Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"autocomplete": "current-password", "class": "input"}),
    )

class GettingStartedResponseForm(forms.ModelForm):
    class Meta:
        model = GettingStartedResponse
        fields = ['end_of_course_hope', 'strengths', 'practice_time', 'practice_location', 'prep_time']
        widgets = {
            'end_of_course_hope': forms.Textarea(attrs={'class': 'textarea'}),
            'strengths': forms.Textarea(attrs={'class': 'textarea'}),
            'practice_time': forms.Textarea(attrs={'class': 'textarea'}),
            'practice_location': forms.Textarea(attrs={'class': 'textarea'}),
            'prep_time': forms.Textarea(attrs={'class': 'textarea'}),
        }

class FormalPracticeForm(forms.ModelForm):
    class Meta:
        model = FormalPractice
        exclude = ('mbsr_user', 'date')

        widgets = {
            'comment': forms.Textarea(attrs={'class': 'textarea'}),
        }

class InformalPracticeForm(forms.ModelForm):
    class Meta:
        model = InformalPractice
        # fields = '__all__'
        exclude = ('mbsr_user', 'date')
        widgets = {
            'situation': forms.Textarea(attrs={'class': 'textarea'}),
            'feelings_before': forms.Textarea(attrs={'class': 'textarea'}),
            'feelings_during': forms.Textarea(attrs={'class': 'textarea'}),
            'learned': forms.Textarea(attrs={'class': 'textarea'}),
            'feelings_now': forms.Textarea(attrs={'class': 'textarea'}),
        }

MBSR_App/views.py
from django.shortcuts import render, redirect
from .forms import GettingStartedResponseForm, FormalPracticeForm, InformalPracticeForm, MyUserCreationForm, MyLoginForm
from .models import GettingStartedResponse, FormalPractice, InformalPractice, MBSRUser, FormalPracticePromptInfo, InformalPracticeInfo
from django.contrib.auth.models import User
from django.views.generic.edit import CreateView, FormView, DeleteView, BaseDetailView
from django.views.generic.base import TemplateView, RedirectView
from django.views import View
from django.views.generic.detail import DetailView
from django.views.generic.list import ListView
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout as auth_logout
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.views import LoginView, LogoutView
from django import forms
from django.urls import reverse
from datetime import date
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib import messages
from django.views.defaults import page_not_found
import datetime
from .util.MBSRUserUpdatesMixin import MBSRUserUpdatesMixin

class GettingStartedCreateView(LoginRequiredMixin, CreateView):
    login_url = 'mbsr_app:index'
    form_class = GettingStartedResponseForm
    model = GettingStartedResponse

    def form_valid(self, form):
        user = User.objects.get(id = self.request.user.id)
        mbsr_user = MBSRUser.objects.get(user=user)

        mbsr_user.has_started = True
        mbsr_user.is_in_week = 1
        mbsr_user.save()

        form.instance.mbsr_user = mbsr_user

        return super().form_valid(form)

    def get_success_url(self):
        return reverse('mbsr_app:account_home_view', kwargs={'pk': self.object.mbsr_user.id})

class GettingStartedDetailView(LoginRequiredMixin, DetailView):
    login_url = 'mbsr_app:index'
    template_name = "mbsr_app/gettingstartedresponse_detail.html"

    def get_mbsr_user(self):
        user = User.objects.get(id = self.request.user.id)
        return MBSRUser.objects.get(user=user)

    def get_object(self):
        try:
            obj = GettingStartedResponse.objects.get(mbsr_user=self.get_mbsr_user().id)
            print("TRY SUCCESSFUL")
            return obj
        except:
            print("FAILURE")
            messages.error(self.request, 'Info not found.')
            return reverse('mbsr_app:account_home_view', kwargs={'pk': self.get_mbsr_user()})

class FormalPracticeCreateView(LoginRequiredMixin, CreateView, MBSRUserUpdatesMixin):
    login_url = 'mbsr_app:index'
    model = FormalPractice
    form_class = FormalPracticeForm

    def form_invalid(self, form):
        return super().form_invalid(form)

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)
    
    def form_valid(self, form):
        mbsr_user = MBSRUser.objects.get(user_id = self.request.user.id) 
        form.instance.mbsr_user = mbsr_user
        form.instance.date = self.get_date()
        form.instance.day = mbsr_user.day_of_week
        form.instance.week = mbsr_user.is_in_week
        form.save()
        self.update_practice_logs("formal")
        return super().form_valid(form)

    def get_user(self):
        return MBSRUser.objects.get(user=self.request.user.id)

    def get_success_url(self):
        return reverse('mbsr_app:account_home_view', kwargs={'pk': self.object.mbsr_user.id})

    def get_context_data(self, **kwargs):
        context = super(FormalPracticeCreateView, self).get_context_data(**kwargs)
        week = MBSRUser.objects.get(user_id = self.request.user.id).is_in_week
        date = datetime.date.today()
        context['date'] = date.strftime("%A %d. %B %Y")
        context['week'] = week
        context['instructions'] = FormalPracticePromptInfo.objects.get(week=week)
        return context

class FormalPracticeListView(LoginRequiredMixin, ListView):
    model = FormalPractice

    def get_user(self):
        return MBSRUser.objects.get(user=self.request.user.id)

    def get_queryset(self):
        return FormalPractice.objects.filter(mbsr_user=self.get_user()).order_by("-date")

class FormalPracticeDetailView(LoginRequiredMixin, DetailView):
    login_url = 'mbsr_app:index'
    template_name = "mbsr_app/formalpractice_view.html"

    def get_user(self):
        return MBSRUser.objects.get(user=self.request.user.id)

    def get_object(self):
        print("DATE: ", self.kwargs['date'])
        return FormalPractice.objects.get(mbsr_user=self.get_user(), date=self.kwargs['date'])

class InformalPracticeCreateView(LoginRequiredMixin, CreateView, MBSRUserUpdatesMixin):
    login_url = 'mbsr_app:index'
    model = InformalPractice
    form_class = InformalPracticeForm

    def form_valid(self, form):
        # mbsr_user = MBSRUser.objects.get(user_id = self.request.user.id) 
        mbsr_user = self.get_user()
        form.instance.mbsr_user = mbsr_user
        form.instance.date = self.get_date()
        form.instance.week = mbsr_user.is_in_week
        form.instance.day = mbsr_user.day_of_week
        form.save()
        self.update_practice_logs("informal")
        return super().form_valid(form) 

    def get_user(self):
        return MBSRUser.objects.get(user=self.request.user.id)

    def get_success_url(self):
        return reverse('mbsr_app:account_home_view', kwargs={'pk': self.object.mbsr_user.id})

    def get_context_data(self, **kwargs):
        context = super(InformalPracticeCreateView, self).get_context_data(**kwargs)
        week = MBSRUser.objects.get(user_id = self.request.user.id).is_in_week
        date = datetime.date.today()
        context['date'] = date.strftime("%A, %B %d, %Y")
        context['week'] = week
        context['instructions'] = InformalPracticeInfo.objects.get(week=week)
        return context

class InformalPracticeDetailView(LoginRequiredMixin, DetailView):
    login_url = 'mbsr_app:index'
    
    template_name = "mbsr_app/informalpractice_view.html"
    # model = InformalPractice

    def get_user(self):
        return MBSRUser.objects.get(user=self.request.user.id)

    def get_object(self):
        print("DATE: ", self.kwargs['date'])
        return InformalPractice.objects.get(mbsr_user=self.get_user(), date=self.kwargs['date'])

    def get_context_data(self, **kwargs):
        context = super(InformalPracticeDetailView, self).get_context_data(**kwargs)
        context['instructions'] = InformalPracticeInfo.objects.get(week=self.get_user().is_in_week)
        return context

class InformalPracticeListView(LoginRequiredMixin, ListView):
    model = InformalPractice

    def get_user(self):
        return MBSRUser.objects.get(user=self.request.user.id)

    def get_queryset(self):
        return InformalPractice.objects.filter(mbsr_user=self.get_user())
    
class IndexView(View):
    def get(self, request):
        form_classes = { 
            'login': AuthenticationForm,
            'signup': MyUserCreationForm,
        }
        return render(request, 'mbsr_app/index.html', form_classes)

class SignUpView(CreateView):
    form_class = MyUserCreationForm
    template_name = "mbsr_app/register_new_user.html"
    
    def form_valid(self,form):
        print("FORM VALID")
        new_user = self.create_new_mbsr_user(form)
        new_user = form.save()
        if new_user is not None:
            login(self.request, new_user)
            return redirect('mbsr_app:account_home_view', pk = new_user.id)
        else:
            return super().form_invalid(form)
            # return redirect('/mbsr/signup_view/') 

    def form_invalid(self, form):
        print("<<<<<-----FORM INVALID----->>>>>")
        print("FORM ERRORS: ", form.errors)
        return super().form_invalid(form)

    def create_new_mbsr_user(self, form):
        username=form.cleaned_data['username']
        # email=form.cleaned_data['email']
        password=form.cleaned_data['password1']

        # new_user = User.objects.create_user(username, email, password)
        # new_user.save()

        self.object = form.save()

        new_mbsr_user = MBSRUser(user=self.object)
        new_mbsr_user.save()

        user = authenticate(username=username, password=password)

        return user

class MyLoginView(LoginView):
    form_class = MyLoginForm
    def get_success_url(self):
        url = 'mbsr_app:account_view_redirect'
        return reverse(url)

# def logout(request):
#     django_logout(request)
#     return redirect("mbsr_app:index")

class MyLogoutView(LogoutView):
    def dispatch(self, request, *args, **kwargs):
        auth_logout(request)
        next_page = reverse('mbsr_app:index')
        if next_page:
            # Redirect to this page until the session has been cleared.
            return redirect(next_page)
        return super().dispatch(request, *args, **kwargs)


class AccountHomeView(LoginRequiredMixin, DetailView):
    login_url = 'mbsr_app:index'
    
    template_name = "mbsr_app/account_home.html"
    model = MBSRUser

    def get_object(self):
        # return User.objects.get(id=self.request.user.id)
        return MBSRUser.objects.get(user_id = self.request.user.id) 

    def get_context_data(self, **kwargs):
        # mbsr_user = MBSRUser.objects.get(user_id = self.request.user.id) 
        mbsr_user = self.get_object()
        formal_practice_qs = FormalPractice.objects.filter(mbsr_user=self.get_object()).order_by('-date')
        formal_practice_exists = formal_practice_qs.filter(mbsr_user=self.get_object(),date__contains = date.today()).exists()
        informal_practice_exists = InformalPractice.objects.filter(mbsr_user=self.get_object(),date__contains = date.today()).exists()

        context = super(AccountHomeView, self).get_context_data()

        today = date.today()

        context['formal_practice_exists'] = formal_practice_exists
        context['informal_practice_exists'] = informal_practice_exists

MBSR_App/templates/MBSR_App/account_home.html
{% extends 'base.html' %}
{% block content %}
<h2 class="center-text title is-2">
    Welcome, {{ user }}!
</h2>
{% if object.has_started %}
<div>
    <h3 class="title is-3 center-text">Week {{ object.is_in_week }} - Day {{ day_of_mbsr_week }}</h3>
    <div class="level">
        <div class="level-item has-text-centered">
            <div class="block">
                <div class="block">
                {% if not formal_practice_exists %}
                    <a class="button is-primary btn-full-width" href="{% url 'mbsr_app:formal_practice_create_view' %}">Log Today's Formal Practice</a>
                    </div>
                {% else %}
                    <!-- <h4 class="block title is-4 mb-5">Today's Formal Practice is complete!</h4> -->
                    <a class="button is-info" href="{% url 'mbsr_app:formal_practice_detail_view' date=date_today %}">View Today's Formal Practice Entry</a>
                </div>
                {% endif %}
                <div class="block">
                    <a class="button is-warning" href="{% url 'mbsr_app:formal_practice_list_view' %}">View Past Formal Practice Entries</a>
                </div>
            </div>
        </div>
        <div class="level-item has-text-centered">
            <div class="block">
                <div class="block">
                {% if not informal_practice_exists %}
                    <a class="button is-primary btn-full-width" href="{% url 'mbsr_app:informal_practice_create_view' %}">Log Today's Informal Practice</a>
                </div>
                {% else %}
                    <!-- <h4 class="block title is-4 mb-5">Today's Informal Practice is complete!</h4> -->
                    <a class="button is-info" href="{% url 'mbsr_app:informal_practice_detail_view' date=date_today %}">View Today's Informal Practice Entry</a>
                </div>
                {% endif %}
                <div class="block">
                    <a class="button is-warning" href="{% url 'mbsr_app:informal_practice_list_view' %}">View Past Informal Practice Entries</a>
                </div>
            </div>
        </div>
    </div>
    <div class="level">
        <div class="level-item has-text-centered">
            <div class="block">
                <div class="block">
                    <a class="button is-warning" href="{% url 'mbsr_app:getting_started_detail_view' %}">View Getting Started Responses</a>
                </div>
            </div>
        </div>
    </div>
</div>

{% else %}
<div class="level">
    <div class="level-item has-text-centered">
        <div class="block">
            <a class="button is-primary is-large" href="{% url 'mbsr_app:getting_started_create_view' %}">Get Started</a>
        </div>
    </div>
</div>
{% endif %}
{% endblock %}

MBSR_App/templates/MBSR_App/formalpractice_form.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="title">Formal Practice Form - Week {{ week }} - {{ date }}</h1>
    {% if instructions.title %}
    {{ instructions.title }}
    {% endif %}
    <div class="block">
        {{ instructions.text|safe }}
    </div>
    <form method="post">
        {% csrf_token %}
        <div class="field">
            <div class="control">
                {{ form.comment }}
            </div>
        </div>
        <button class="button is-info" type="submit">Submit</button>
    </form>
</div>
{% endblock %}

MBSR_App/templates/MBSR_App/formalpractice_list.html
{% extends 'base.html' %}
{% block content %}
<h2 class="title is-2 center-text">Formal Practice Log</h2>
<div class="columns">
    <div class="column">
        {% for entry in object_list %}
        <div class="level">
            <div class="level-item">
                <a href="{% url 'mbsr_app:formal_practice_detail_view' date=entry.date %}">
                    Week {{ entry.week }},
                    Day {{ entry.day }} - 
                    {{ entry.date }}
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

MBSR_App/templates/MBSR_App/formalpractice_view.html
{% extends 'base.html' %}
{% block content %}
<div class="block">
    <h2 class="title is-2 center-text">Formal Practice View</h2>
    <h3 class="title is-3 center-text">Week {{ object.week }}, Day {{ object.day }}</h3>
    <h4 class="title is-4 center-text">{{ object.date }}</h4>
</div>
<div class="block box">
    {{ object.comment }}
</div>
<div>
    <a class="button is-warning" href="{% url 'mbsr_app:formal_practice_list_view' %}">Back</a>
</div>
<div>
    {#<a href="{% url '' %}">View Another Entry</a>#}
</div>

{% endblock %}

MBSR_App/templates/MBSR_App/gettingstartedresponse_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="title">Getting Started Responses</h1>
</div>
<h1 class="title">Getting Started</h1>
    <div class="block">
            This questionnaire begins your MBSR journey. Recording your responses to these questions and those on the
    practice logs will help ground your practice and learnings in a way that would not be possible if you simply answered
    these questions in your head. In a way, this is the first mindfulness practice: being mindful of your intentions and
    commitment to the process you are about to begin.
    </div>

        <div class="block">
            So, first, there is probably something that drew you to this program that made it seem like a good idea. For
            example, you may wake up in the middle of the night with worries and concerns that keep you from getting a good
            night’s sleep, or you may be dealing with health issues, and you’ve heard that mindfulness can help you deal with
            them, or you may have trouble concentrating, or you may simply want to increase your ability to be present and
            fully engaged in life, to accept more fully yourself/others, just as you/they are.
        </div>
        <div class="block"><strong>By the end of the course, I am hoping that: </strong></div>
        <div class="block box">{{ object.end_of_course_hope }}</div>
        
        <div class="block">
            While there are things you hope that will get better, it is important to recognize positive aspects of yourself,
    because it is these things that form the base for any self-improvement. We tend to take for granted our own core
    strengths, so give yourself a few minutes to reflect on this. For instance, what would a good friend or close family
    member say that they appreciate about you?
        </div>
        <div class="block"><strong>Some of my strengths are: </strong></div>
        <div class="block box">{{ object.strengths }}</div>
        
        <div class="block">
            Finding a specific time and place for your half-hour of daily practice is likely to be one of the most difficult
    hurdles, and writing down now when and where you’ll be doing your daily practice will help you to keep your promise
    to yourself to practice each day. People often choose to practice first thing in the morning, before roommates or
    family members are up and about, and others like the evening shortly before bedtime, or just after arriving home
    from work. Precisely when you practice is less important than having a set time and place, a time that you know you
    can practice without having to attend to the telephone or be responsive to others, and a place that is quiet and
    separate from others.
        </div>
        <div class="block"><strong>When will I practice? (Try to be concrete, e.g., 6:30am M-F, 7:30am Sat/Sun): </strong></div>
        <div class="block box">{{ object.practice_time }}</div>

        <div class="block"><strong>Where I am planning to practice (e.g., corner of the bedroom, basement, etc.):</strong></div>
        <div class="block box">{{ object.practice_location }}</div>
        
        <div class="block">
            In addition, you will want to allow time each week to prepare for the coming week’s practice by watching that
    week’s videos and/or starting the reading indicated for that week. Since we recommend practicing six days a week,
    you could choose to prepare for the coming week on the seventh day, starting at the same time you normally would
    practice. On this day, it’s best to reserve a time period of 60-90 minutes.
        </div>
        <div class="block"><strong>The time & day of the week I will get ready for the coming week’s practice is: </strong></div>
        <div class="block box">{{ object.prep_time }}</div>
        <a class="button is-warning" href="{% url 'mbsr_app:account_home_view' pk=user.id %}">Back</a>
{% endblock %}

MBSR_App/templates/MBSR_App/index.html
{% extends 'base.html' %}
{% block content %}
<section class="hero is-fullheight-with-navbar">
    <div class="hero-body">
        <div class="container has-text-centered">
            <div class="level">
                <div class="level-item">
                    <h1 class="title is-1 center-text">MBSR</h1>
                </div>
            </div>
            <div class="level">
                <div class="level-item">
                    <h2 class="title is-2 center-text">Mindfulness-Based Stress Reduction</h2>
                </div>
            </div>
            <div class="level">
                <div class="level-item">
                    <h3 class="subtitle is-3">Log your daily practice for the MSBR program presented by</h3>
                </div>            
            </div>
            <div class="level">
                <div class="level-item">
                    <h3 class="subtitle is-3"><a href="https://palousemindfulness.com/" target="_blank">palousemindfulness.com</a></h3>
                </div>
            </div>
            <div class="level buttons are-large">
                <!-- <div class="level-left"> -->
                    <div class="level-item">
                        <a href="{% url 'mbsr_app:signup_view' %}" class="button is-warning">
                            <strong>Sign up</strong>
                        </a>
                    </div>
                <!-- </div> -->
                <!-- <div class="level-right"> -->
                    <div class="level-item">
                        <a href="{% url 'mbsr_app:login' %}" class="button is-primary">
                            Log in
                        </a>
                    </div>
                <!-- </div> -->
            </div>  
        </div>        
    </div>
</section>
{% endblock %}

MBSR_App/templates/MBSR_App/informalpractice_list.html
{% extends 'base.html' %}
{% block content %}

<h2 class="title is-2 center-text">Informal Practice Log</h2>
<div class="columns">
    <div class="column">
        {% for entry in object_list %}
        <div class="level">
            <div class="level-item">
                <a href="{% url 'mbsr_app:informal_practice_detail_view' date=entry.date %}">
                    Week {{ entry.week }},
                    Day {{ entry.day }} - 
                    {{ entry.date }}
                </a>
            </div>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

MBSR_App/templates/MBSR_App/informalpractice_view.html
{% extends 'base.html' %}
{% block content %}

<div class="block">
    <h2 class="title is-2 center-text">Informal Practice View</h2>
    <h3 class="title is-3 center-text">Week {{ object.week }}, Day {{ object.day }}</h3>
    <h4 class="title is-4 center-text">{{ object.date }}</h4>
    <h5 class="title is-5 center-text">Informal Practice Form - {{ instructions.title|safe }}</h5> 
</div>
        <div class="block">
            {{ instructions.instructions }}    
        </div>
        <div class="field">
            <label class="label">
                {{ instructions.box_1|safe }}
            </label>
            <div class="box">
                {{ object.situation }}
            </div>
        </div>
        <div class="field">
            <label class="label">
                {{ instructions.box_2|safe }}
            </label>
            <div class="box">
                {{ object.feelings_before }}
            </div>
        </div>
        <div class="field">
            <label class="label">
                {{ instructions.box_3|safe }}
            </label>
            <div class="box">
                {{ object.feelings_during }}
            </div>
        </div>
        <div class="field">
            <label class="label">
                {{ instructions.box_4|safe }}
            </label>
            <div class="box">
                {{ object.learned }}
            </div>
        </div>
        <div class="field">
            <label class="label">
                {{ instructions.box_5|safe }}
            </label>
            <div class="box">
                {{ object.feelings_now }}
            </div>
        </div>
        {% if instructions.box_6 %}
        <div class="field">
            <label class="label">
                {{ instructions.box_6|safe }}
            </label>
            <div class="box">
                {{ object.feelings_now }}
            </div>
        </div>
        {% endif %}
        <div>
            <a class="button is-warning" href="{% url 'mbsr_app:informal_practice_list_view' %}">Back</a>
        </div>

{% endblock %}

MBSR_App/templates/MBSR_App/login.html
{% extends 'base.html' %}
{% block content %}
<div class="container">
    <h1 class="title is-1">Login</h1>
    <form method="post">
        {% csrf_token %}
        {% for field in form %} 
            <div class="field">
                {{ field.errors }}
                <label class="label">{{ field.label }}</label> 
                <div class="control">
                    {{ field }}
                </div>
                {% if field.help_text %}
                <p class="help">{{ field.help_text|safe }}</p>
                {% endif %}
            </div>
        {% endfor %}
        <button type="submit" class="button is-primary">Submit</button>
        <input type="hidden" name="next" value="{{ form.next }}">
    </form>
</div>

{% endblock %}

MBSR_App/templates/MBSR_App/navbar.html
<!-- <nav>
    <div class="pure-menu pure-menu-horizontal">
        <a href="{% url 'mbsr_app:index' %}" class="pure-menu-heading pure-menu-link">MBSR</a>
        <ul class="pure-menu-list">
            {% if user.is_authenticated %}
            <li class="pure-menu-item">
                <a href="{% url 'mbsr_app:account_home_view' pk=user.id %}" class="pure-menu-link">Account Home</a>
            </li>
            <li class="pure-menu-item">
                <a href="{% url 'mbsr_app:logout' %}">Logout</a>
            </li>
            {% else %}
            <li class="pure-menu-item">
                <form method="POST" action="{% url 'mbsr_app:login' %}">
                    {% csrf_token %}
                    {{ login }}
                    <input type="submit"></input>
                    <input type="hidden" name="next" value="/mbsr/account_view_redirect/">
                </form>
            </li>
            {% endif %}
        </ul>
    </div>
</nav> -->

<nav class="navbar" role="navigation" aria-label="main navigation">
    <div class="navbar-brand">
      <a class="navbar-item" href="{% url 'mbsr_app:index' %}">
        <strong>MBSR</strong>
      </a>

    </div>
  
    <div id="navbarBasicExample" class="navbar-menu">
      <div class="navbar-start">
          {% if user.is_authenticated %}
        <a href="{% url 'mbsr_app:account_home_view' pk=user.id %}" class="navbar-item">
          Account Home
        </a>
        {% endif %}
      </div>
  
      <div class="navbar-end">
        <div class="navbar-item">
          <div class="buttons">
            {% if user.is_authenticated %}
            <a href="{% url 'mbsr_app:logout' %}" class="button is-primary">
                <strong>Logout</strong>
              </a>
              {% else %}
            <a href="{% url 'mbsr_app:signup_view' %}" class="button is-warning">
              <strong>Sign up</strong>
            </a>
            <a href="{% url 'mbsr_app:login' %}" class="button is-primary">
              Log in
            </a>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  </nav>